### ISSUE TITLE
AttributeError: 'PromptExecutor' object has no attribute 'outputs'

### ISSUE THREAD

**Issue by qq116** [ali1234/comfyui-job-iterator#6]
I'm a newbie and I don't know where the problem is. The example stopped working.
Thanks so much for reaching out

FETCH DATA from: C:\testAI\test01\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
got prompt
Prompt executor has been patched by Job Iterator!
JobIterator: 1 / 54
model weight dtype torch.float16, manual cast: None
model_type EPS
Using pytorch attention in VAE
Using pytorch attention in VAE
Requested to load SDXLClipModel
Loading 1 new model
loaded completely 0.0 1560.802734375 True
Requested to load SDXL
Loading 1 new model
loaded completely 0.0 4897.0483474731445 True
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:13<00:00,  1.54it/s]
Requested to load TAESD
Loading 1 new model
loaded completely 0.0 4.66358757019043 True
Exception in thread Thread-12 (prompt_worker):
Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "C:\testAI\test01\ComfyUI_windows_portable\ComfyUI\main.py", line 121, in prompt_worker
    e.execute(item[2], prompt_id, item[3], item[4])
  File "C:\testAI\test01\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy\__init__.py", line 217, in rgthree_execute
    return self.rgthree_old_execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\testAI\test01\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-job-iterator\job.py", line 198, in execute
    steps = self.outputs[k][1][0]
            ^^^^^^^^^^^^
AttributeError: 'PromptExecutor' object has no attribute 'outputs'

**Comment by ali1234** [comment]
Totally expected.

There is a new way to do loops and iteration in ComfyUI.

I will fix this repo soon.

**Comment by veighnsche** [comment]
Your nodes are the only way I know how to do loops in comfy. I can't find any info about doing new ways to do loops in comfyUI. can you provide a link maybe?

**Comment by ali1234** [comment]
It's a new API for node pack authors, not a user feature (yet).

You're going to see a lot of new node packs offering various types of looping soon, hopefully.

**Comment by veighnsche** [comment]
For other people coming across this issue:

If you want to continue using job-iterator: Go to the ComfyUI folder > open cmd > enter "git checkout 0f9c2a78224ce3179c773fe3af63722f438b0613 ." > Restart ComfyUI

For another way of doing loops: I use the cyclist extension and memorize the step and recall is again in the next generation. You have to calculate everything from that recalled step.

**Comment by mr-pepe69** [comment]
> For other people coming across this issue:
> 
> If you want to continue using job-iterator: Go to the ComfyUI folder > open cmd > enter "git checkout 0f9c2a78224ce3179c773fe3af63722f438b0613 ." > Restart ComfyUI
> 
> For another way of doing loops: I use the cyclist extension and memorize the step and recall is again in the next generation. You have to calculate everything from that recalled step.

it looks like it was fixed for me with the git checkout command. thanks! any idea if moving fordward i will have to run a different command? i don't want to brake my comfyui install permantently

**Comment by felixsoong0825** [comment]
> For other people coming across this issue:
> 
> If you want to continue using job-iterator: Go to the ComfyUI folder > open cmd > enter "git checkout 0f9c2a78224ce3179c773fe3af63722f438b0613 ." > Restart ComfyUI
> 
> For another way of doing loops: I use the cyclist extension and memorize the step and recall is again in the next generation. You have to calculate everything from that recalled step.

Its like magic, thanks!

**Comment by ali1234** [comment]
Okay, I have fixed this node pack for latest ComfyUI. To fix workflows, just delete the old JobIterator node and replace it with the new JobToList. Be aware that jobs will now execute breadth-first rather than depth first. This is okay (and faster) for small jobs but might run out of memory for very large ones. In that case you'll have to use the new for-loop mechanism. The current step output is also gone from JobToList. Use EnumerateJob to create a named step attribute (see the new workflow example).

**Comment by ali1234** [comment]
PS I probably won't be updating this pack to enable depth-first execution. If I do that it will be a totally new pack.

**Comment by rondonjon** [comment]
> In that case you'll have to use the new for-loop mechanism.

Could you please elaborate on this, @ali1234 ? I see no such node type and haven't read about loop support in any of the recent ComfyUI releases either, so I am kind of lost here 😓
